# Doc: http://manuel.manuelles.nl/blog/2012/06/22/integrate-travis-ci-into-grunt/

sudo: false

language: node_js

node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - joseph@onsip.com
    on_success: change
    on_failure: always
